apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloakdb
spec:
  instances:
    - replicas: 2
      dataVolumeClaimSpec:
        storageClassName: nfs-client-qnap
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-4
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: nfs-client-qnap
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
